import { DevelopmentCard, GemColor, NobleTile } from './models';

// 10 Noble tiles available in the game
export const noblesData: NobleTile[] = [
  { id: 'n-1', prestigePoints: 3, requiredBonuses: { [GemColor.Sapphire]: 4, [GemColor.Emerald]: 4 } },
  { id: 'n-2', prestigePoints: 3, requiredBonuses: { [GemColor.Ruby]: 4, [GemColor.Emerald]: 4 } },
  { id: 'n-3', prestigePoints: 3, requiredBonuses: { [GemColor.Emerald]: 3, [GemColor.Sapphire]: 3, [GemColor.Ruby]: 3 } },
  { id: 'n-4', prestigePoints: 3, requiredBonuses: { [GemColor.Sapphire]: 4, [GemColor.Diamond]: 4 } },
  { id: 'n-5', prestigePoints: 3, requiredBonuses: { [GemColor.Emerald]: 3, [GemColor.Sapphire]: 3, [GemColor.Diamond]: 3 } },
  { id: 'n-6', prestigePoints: 3, requiredBonuses: { [GemColor.Onyx]: 4, [GemColor.Ruby]: 4 } },
  { id: 'n-7', prestigePoints: 3, requiredBonuses: { [GemColor.Onyx]: 4, [GemColor.Diamond]: 4 } },
  { id: 'n-8', prestigePoints: 3, requiredBonuses: { [GemColor.Onyx]: 3, [GemColor.Sapphire]: 3, [GemColor.Diamond]: 3 } },
  { id: 'n-9', prestigePoints: 3, requiredBonuses: { [GemColor.Onyx]: 3, [GemColor.Ruby]: 3, [GemColor.Diamond]: 3 } },
  { id: 'n-10', prestigePoints: 3, requiredBonuses: { [GemColor.Onyx]: 3, [GemColor.Ruby]: 3, [GemColor.Emerald]: 3 } }
];

// All 90 Development Cards
export const allDevelopmentCards: DevelopmentCard[] = [
  // --- Level 1 Cards ---
  { id: 'c-1', level: 1, colorBonus: GemColor.Onyx, prestigePoints: 1, cost: { [GemColor.Sapphire]: 4 } },
  { id: 'c-2', level: 1, colorBonus: GemColor.Sapphire, prestigePoints: 0, cost: { [GemColor.Onyx]: 3 } },
  { id: 'c-3', level: 1, colorBonus: GemColor.Onyx, prestigePoints: 0, cost: { [GemColor.Diamond]: 2, [GemColor.Sapphire]: 2, [GemColor.Ruby]: 1 } },
  { id: 'c-4', level: 1, colorBonus: GemColor.Emerald, prestigePoints: 1, cost: { [GemColor.Onyx]: 4 } },
  { id: 'c-5', level: 1, colorBonus: GemColor.Emerald, prestigePoints: 0, cost: { [GemColor.Ruby]: 3 } },
  { id: 'c-6', level: 1, colorBonus: GemColor.Ruby, prestigePoints: 0, cost: { [GemColor.Diamond]: 2, [GemColor.Sapphire]: 1, [GemColor.Emerald]: 1, [GemColor.Onyx]: 1 } },
  { id: 'c-7', level: 1, colorBonus: GemColor.Diamond, prestigePoints: 0, cost: { [GemColor.Ruby]: 2, [GemColor.Onyx]: 1 } },
  { id: 'c-8', level: 1, colorBonus: GemColor.Onyx, prestigePoints: 0, cost: { [GemColor.Emerald]: 3 } },
  { id: 'c-9', level: 1, colorBonus: GemColor.Emerald, prestigePoints: 0, cost: { [GemColor.Diamond]: 1, [GemColor.Sapphire]: 1, [GemColor.Ruby]: 1, [GemColor.Onyx]: 1 } },
  { id: 'c-10', level: 1, colorBonus: GemColor.Sapphire, prestigePoints: 0, cost: { [GemColor.Diamond]: 1, [GemColor.Emerald]: 1, [GemColor.Ruby]: 1, [GemColor.Onyx]: 1 } },
  { id: 'c-11', level: 1, colorBonus: GemColor.Ruby, prestigePoints: 0, cost: { [GemColor.Diamond]: 1, [GemColor.Sapphire]: 1, [GemColor.Emerald]: 1, [GemColor.Onyx]: 1 } },
  { id: 'c-12', level: 1, colorBonus: GemColor.Sapphire, prestigePoints: 0, cost: { [GemColor.Sapphire]: 1, [GemColor.Emerald]: 3, [GemColor.Ruby]: 1 } },
  { id: 'c-13', level: 1, colorBonus: GemColor.Sapphire, prestigePoints: 1, cost: { [GemColor.Ruby]: 4 } },
  { id: 'c-14', level: 1, colorBonus: GemColor.Ruby, prestigePoints: 0, cost: { [GemColor.Ruby]: 2, [GemColor.Diamond]: 2 } },
  { id: 'c-15', level: 1, colorBonus: GemColor.Diamond, prestigePoints: 0, cost: { [GemColor.Diamond]: 3, [GemColor.Sapphire]: 1, [GemColor.Onyx]: 1 } },
  { id: 'c-16', level: 1, colorBonus: GemColor.Onyx, prestigePoints: 0, cost: { [GemColor.Emerald]: 2, [GemColor.Ruby]: 1 } },
  { id: 'c-17', level: 1, colorBonus: GemColor.Emerald, prestigePoints: 0, cost: { [GemColor.Sapphire]: 2, [GemColor.Ruby]: 2 } },
  { id: 'c-18', level: 1, colorBonus: GemColor.Sapphire, prestigePoints: 0, cost: { [GemColor.Emerald]: 2, [GemColor.Onyx]: 2 } },
  { id: 'c-19', level: 1, colorBonus: GemColor.Ruby, prestigePoints: 0, cost: { [GemColor.Diamond]: 3 } },
  { id: 'c-20', level: 1, colorBonus: GemColor.Diamond, prestigePoints: 0, cost: { [GemColor.Sapphire]: 2, [GemColor.Emerald]: 2, [GemColor.Onyx]: 1 } },
  { id: 'c-21', level: 1, colorBonus: GemColor.Onyx, prestigePoints: 0, cost: { [GemColor.Diamond]: 1, [GemColor.Sapphire]: 2, [GemColor.Emerald]: 1, [GemColor.Ruby]: 1 } },
  { id: 'c-22', level: 1, colorBonus: GemColor.Emerald, prestigePoints: 0, cost: { [GemColor.Diamond]: 1, [GemColor.Sapphire]: 1, [GemColor.Ruby]: 1, [GemColor.Onyx]: 2 } },
  { id: 'c-23', level: 1, colorBonus: GemColor.Sapphire, prestigePoints: 0, cost: { [GemColor.Diamond]: 1, [GemColor.Onyx]: 2 } },
  { id: 'c-24', level: 1, colorBonus: GemColor.Onyx, prestigePoints: 0, cost: { [GemColor.Diamond]: 1, [GemColor.Sapphire]: 1, [GemColor.Emerald]: 1, [GemColor.Ruby]: 1 } },
  { id: 'c-25', level: 1, colorBonus: GemColor.Emerald, prestigePoints: 0, cost: { [GemColor.Sapphire]: 1, [GemColor.Ruby]: 2, [GemColor.Onyx]: 2 } },
  { id: 'c-26', level: 1, colorBonus: GemColor.Sapphire, prestigePoints: 0, cost: { [GemColor.Diamond]: 1, [GemColor.Emerald]: 2, [GemColor.Ruby]: 2 } },
  { id: 'c-27', level: 1, colorBonus: GemColor.Ruby, prestigePoints: 0, cost: { [GemColor.Diamond]: 1, [GemColor.Ruby]: 1, [GemColor.Onyx]: 3 } },
  { id: 'c-28', level: 1, colorBonus: GemColor.Diamond, prestigePoints: 0, cost: { [GemColor.Sapphire]: 2, [GemColor.Onyx]: 2 } },
  { id: 'c-29', level: 1, colorBonus: GemColor.Diamond, prestigePoints: 0, cost: { [GemColor.Sapphire]: 1, [GemColor.Emerald]: 1, [GemColor.Ruby]: 1, [GemColor.Onyx]: 1 } },
  { id: 'c-30', level: 1, colorBonus: GemColor.Sapphire, prestigePoints: 0, cost: { [GemColor.Diamond]: 1, [GemColor.Emerald]: 1, [GemColor.Ruby]: 2, [GemColor.Onyx]: 1 } },
  { id: 'c-31', level: 1, colorBonus: GemColor.Onyx, prestigePoints: 0, cost: { [GemColor.Diamond]: 2, [GemColor.Emerald]: 2 } },
  { id: 'c-32', level: 1, colorBonus: GemColor.Emerald, prestigePoints: 0, cost: { [GemColor.Diamond]: 1, [GemColor.Sapphire]: 3, [GemColor.Emerald]: 1 } },
  { id: 'c-33', level: 1, colorBonus: GemColor.Emerald, prestigePoints: 0, cost: { [GemColor.Diamond]: 2, [GemColor.Sapphire]: 1 } },
  { id: 'c-34', level: 1, colorBonus: GemColor.Diamond, prestigePoints: 1, cost: { [GemColor.Emerald]: 4 } },
  { id: 'c-35', level: 1, colorBonus: GemColor.Diamond, prestigePoints: 0, cost: { [GemColor.Sapphire]: 1, [GemColor.Emerald]: 2, [GemColor.Ruby]: 1, [GemColor.Onyx]: 1 } },
  { id: 'c-36', level: 1, colorBonus: GemColor.Diamond, prestigePoints: 0, cost: { [GemColor.Sapphire]: 3 } },
  { id: 'c-37', level: 1, colorBonus: GemColor.Onyx, prestigePoints: 0, cost: { [GemColor.Emerald]: 1, [GemColor.Ruby]: 3, [GemColor.Onyx]: 1 } },
  { id: 'c-38', level: 1, colorBonus: GemColor.Ruby, prestigePoints: 1, cost: { [GemColor.Diamond]: 4 } },
  { id: 'c-39', level: 1, colorBonus: GemColor.Ruby, prestigePoints: 0, cost: { [GemColor.Diamond]: 2, [GemColor.Emerald]: 1, [GemColor.Onyx]: 2 } },
  { id: 'c-40', level: 1, colorBonus: GemColor.Ruby, prestigePoints: 0, cost: { [GemColor.Sapphire]: 2, [GemColor.Emerald]: 1 } },

  // --- Level 2 Cards ---
  { id: 'c-41', level: 2, colorBonus: GemColor.Onyx, prestigePoints: 2, cost: { [GemColor.Sapphire]: 1, [GemColor.Emerald]: 4, [GemColor.Ruby]: 2 } },
  { id: 'c-42', level: 2, colorBonus: GemColor.Diamond, prestigePoints: 2, cost: { [GemColor.Emerald]: 1, [GemColor.Ruby]: 4, [GemColor.Onyx]: 2 } },
  { id: 'c-43', level: 2, colorBonus: GemColor.Sapphire, prestigePoints: 2, cost: { [GemColor.Diamond]: 2, [GemColor.Ruby]: 1, [GemColor.Onyx]: 4 } },
  { id: 'c-44', level: 2, colorBonus: GemColor.Sapphire, prestigePoints: 2, cost: { [GemColor.Diamond]: 5, [GemColor.Sapphire]: 3 } },
  { id: 'c-45', level: 2, colorBonus: GemColor.Ruby, prestigePoints: 2, cost: { [GemColor.Diamond]: 3, [GemColor.Onyx]: 5 } },
  { id: 'c-46', level: 2, colorBonus: GemColor.Emerald, prestigePoints: 2, cost: { [GemColor.Diamond]: 4, [GemColor.Sapphire]: 2, [GemColor.Onyx]: 1 } },
  { id: 'c-47', level: 2, colorBonus: GemColor.Sapphire, prestigePoints: 2, cost: { [GemColor.Sapphire]: 5 } },
  { id: 'c-48', level: 2, colorBonus: GemColor.Onyx, prestigePoints: 2, cost: { [GemColor.Diamond]: 5 } },
  { id: 'c-49', level: 2, colorBonus: GemColor.Diamond, prestigePoints: 2, cost: { [GemColor.Ruby]: 5, [GemColor.Onyx]: 3 } },
  { id: 'c-50', level: 2, colorBonus: GemColor.Ruby, prestigePoints: 2, cost: { [GemColor.Onyx]: 5 } },
  { id: 'c-51', level: 2, colorBonus: GemColor.Emerald, prestigePoints: 2, cost: { [GemColor.Emerald]: 5 } },
  { id: 'c-52', level: 2, colorBonus: GemColor.Ruby, prestigePoints: 1, cost: { [GemColor.Diamond]: 2, [GemColor.Ruby]: 2, [GemColor.Onyx]: 3 } },
  { id: 'c-53', level: 2, colorBonus: GemColor.Emerald, prestigePoints: 1, cost: { [GemColor.Diamond]: 3, [GemColor.Emerald]: 2, [GemColor.Ruby]: 3 } },
  { id: 'c-54', level: 2, colorBonus: GemColor.Sapphire, prestigePoints: 1, cost: { [GemColor.Sapphire]: 2, [GemColor.Emerald]: 3, [GemColor.Onyx]: 3 } },
  { id: 'c-55', level: 2, colorBonus: GemColor.Onyx, prestigePoints: 1, cost: { [GemColor.Diamond]: 3, [GemColor.Emerald]: 3, [GemColor.Onyx]: 2 } },
  { id: 'c-56', level: 2, colorBonus: GemColor.Diamond, prestigePoints: 3, cost: { [GemColor.Diamond]: 6 } },
  { id: 'c-57', level: 2, colorBonus: GemColor.Ruby, prestigePoints: 2, cost: { [GemColor.Diamond]: 1, [GemColor.Sapphire]: 4, [GemColor.Emerald]: 2 } },
  { id: 'c-58', level: 2, colorBonus: GemColor.Onyx, prestigePoints: 3, cost: { [GemColor.Onyx]: 6 } },
  { id: 'c-59', level: 2, colorBonus: GemColor.Diamond, prestigePoints: 1, cost: { [GemColor.Emerald]: 3, [GemColor.Ruby]: 2, [GemColor.Onyx]: 2 } },
  { id: 'c-60', level: 2, colorBonus: GemColor.Onyx, prestigePoints: 1, cost: { [GemColor.Diamond]: 3, [GemColor.Sapphire]: 2, [GemColor.Emerald]: 2 } },
  { id: 'c-61', level: 2, colorBonus: GemColor.Sapphire, prestigePoints: 1, cost: { [GemColor.Sapphire]: 2, [GemColor.Emerald]: 2, [GemColor.Ruby]: 3 } },
  { id: 'c-62', level: 2, colorBonus: GemColor.Emerald, prestigePoints: 3, cost: { [GemColor.Emerald]: 6 } },
  { id: 'c-63', level: 2, colorBonus: GemColor.Emerald, prestigePoints: 1, cost: { [GemColor.Diamond]: 2, [GemColor.Sapphire]: 3, [GemColor.Onyx]: 2 } },
  { id: 'c-64', level: 2, colorBonus: GemColor.Onyx, prestigePoints: 2, cost: { [GemColor.Emerald]: 5, [GemColor.Ruby]: 3 } },
  { id: 'c-65', level: 2, colorBonus: GemColor.Sapphire, prestigePoints: 3, cost: { [GemColor.Sapphire]: 6 } },
  { id: 'c-66', level: 2, colorBonus: GemColor.Emerald, prestigePoints: 2, cost: { [GemColor.Emerald]: 3, [GemColor.Sapphire]: 5 } },
  { id: 'c-67', level: 2, colorBonus: GemColor.Ruby, prestigePoints: 1, cost: { [GemColor.Sapphire]: 3, [GemColor.Ruby]: 2, [GemColor.Onyx]: 3 } },
  { id: 'c-68', level: 2, colorBonus: GemColor.Diamond, prestigePoints: 1, cost: { [GemColor.Diamond]: 2, [GemColor.Sapphire]: 3, [GemColor.Ruby]: 3 } },
  { id: 'c-69', level: 2, colorBonus: GemColor.Diamond, prestigePoints: 2, cost: { [GemColor.Ruby]: 5 } },
  { id: 'c-70', level: 2, colorBonus: GemColor.Ruby, prestigePoints: 3, cost: { [GemColor.Ruby]: 6 } },

  // --- Level 3 Cards ---
  { id: 'c-71', level: 3, colorBonus: GemColor.Onyx, prestigePoints: 4, cost: { [GemColor.Emerald]: 3, [GemColor.Ruby]: 6, [GemColor.Onyx]: 3 } },
  { id: 'c-72', level: 3, colorBonus: GemColor.Ruby, prestigePoints: 4, cost: { [GemColor.Sapphire]: 3, [GemColor.Emerald]: 6, [GemColor.Ruby]: 3 } },
  { id: 'c-73', level: 3, colorBonus: GemColor.Sapphire, prestigePoints: 4, cost: { [GemColor.Diamond]: 7 } },
  { id: 'c-74', level: 3, colorBonus: GemColor.Diamond, prestigePoints: 4, cost: { [GemColor.Onyx]: 7 } },
  { id: 'c-75', level: 3, colorBonus: GemColor.Emerald, prestigePoints: 4, cost: { [GemColor.Diamond]: 3, [GemColor.Sapphire]: 6, [GemColor.Emerald]: 3 } },
  { id: 'c-76', level: 3, colorBonus: GemColor.Emerald, prestigePoints: 4, cost: { [GemColor.Sapphire]: 7 } },
  { id: 'c-77', level: 3, colorBonus: GemColor.Onyx, prestigePoints: 4, cost: { [GemColor.Ruby]: 7 } },
  { id: 'c-78', level: 3, colorBonus: GemColor.Diamond, prestigePoints: 4, cost: { [GemColor.Diamond]: 3, [GemColor.Ruby]: 3, [GemColor.Onyx]: 6 } },
  { id: 'c-79', level: 3, colorBonus: GemColor.Ruby, prestigePoints: 4, cost: { [GemColor.Emerald]: 7 } },
  { id: 'c-80', level: 3, colorBonus: GemColor.Sapphire, prestigePoints: 4, cost: { [GemColor.Diamond]: 6, [GemColor.Sapphire]: 3, [GemColor.Onyx]: 3 } },
  { id: 'c-81', level: 3, colorBonus: GemColor.Onyx, prestigePoints: 3, cost: { [GemColor.Diamond]: 3, [GemColor.Sapphire]: 3, [GemColor.Emerald]: 5, [GemColor.Ruby]: 3 } },
  { id: 'c-82', level: 3, colorBonus: GemColor.Emerald, prestigePoints: 3, cost: { [GemColor.Diamond]: 5, [GemColor.Sapphire]: 3, [GemColor.Ruby]: 3, [GemColor.Onyx]: 3 } },
  { id: 'c-83', level: 3, colorBonus: GemColor.Sapphire, prestigePoints: 3, cost: { [GemColor.Diamond]: 3, [GemColor.Emerald]: 3, [GemColor.Ruby]: 3, [GemColor.Onyx]: 5 } },
  { id: 'c-84', level: 3, colorBonus: GemColor.Diamond, prestigePoints: 3, cost: { [GemColor.Sapphire]: 3, [GemColor.Emerald]: 3, [GemColor.Ruby]: 5, [GemColor.Onyx]: 3 } },
  { id: 'c-85', level: 3, colorBonus: GemColor.Ruby, prestigePoints: 3, cost: { [GemColor.Diamond]: 3, [GemColor.Sapphire]: 5, [GemColor.Emerald]: 3, [GemColor.Onyx]: 3 } },
  { id: 'c-86', level: 3, colorBonus: GemColor.Onyx, prestigePoints: 5, cost: { [GemColor.Ruby]: 7, [GemColor.Onyx]: 3 } },
  { id: 'c-87', level: 3, colorBonus: GemColor.Ruby, prestigePoints: 5, cost: { [GemColor.Emerald]: 7, [GemColor.Ruby]: 3 } },
  { id: 'c-88', level: 3, colorBonus: GemColor.Diamond, prestigePoints: 5, cost: { [GemColor.Diamond]: 3, [GemColor.Onyx]: 7 } },
  { id: 'c-89', level: 3, colorBonus: GemColor.Emerald, prestigePoints: 5, cost: { [GemColor.Sapphire]: 7, [GemColor.Emerald]: 3 } },
  { id: 'c-90', level: 3, colorBonus: GemColor.Sapphire, prestigePoints: 5, cost: { [GemColor.Diamond]: 7, [GemColor.Sapphire]: 3 } }
];

// Exporting categorized cards for easy setup
export const level1Cards = allDevelopmentCards.filter(c => c.level === 1);
export const level2Cards = allDevelopmentCards.filter(c => c.level === 2);
export const level3Cards = allDevelopmentCards.filter(c => c.level === 3);
